import { MerchantChain } from './merchant-chain';

export class Merchant {
	cmrMerchantId: string;
	cmrTransSale: string;
	cmrCloseTime: string;
	cmrAccessType: string;
	cmrAccessTrx: string;
	cmrPropina: string;
	cmrLastNumber: string;
	cmrReqDNI: string;
	cmrDigitKey: string;
	cmrVoidKey: string;
	cmrCardWriter: string;
	cmrPaymentKey: string;
	cmrDepartCode: string;
	cmrConfigKey: string;
	cmrStatus: string;
	cmrTransCash: string;
	cmrTransGas: string;
	cmrMCC: string;
	cmrMoneyMult: string;
	hmrModifyTime: string;
	cmrNetBin: string;
	cmrProfileId: string;
	dmrPhone: string;
	dmrAddress: string;
	cmrRucCode: string;
	cmrCloseType: string;
	cmrSettleKey: string;
	nmrFreqSettle: string;
	cmrTerminals: string;
	cmrComision: string;
	cmrEmail: string;
	cmrModifyUser: string;
	fmrModifyDate: string;
	cmrReqCashBack: string;
	cmrTransAnular: string;
	cmrForceUpdate: string;
	cmrTransPropina: string;
	cmrDistrictCode: string;
	cmrValOperator: string;
	cmrLimitAmountDollar: string;
	cmrMerchantChain: MerchantChain[];
	hmrBatchCloseHour: string;
	dmrMerchantName: string;
	cmrLogicalStatus: string;
	cmrTransPreAutorization: string;
	cmrTransAnularPS: string;
	fmrContrSignDate: string;
	cmrSaldoAmount: string;
	cmrProvinceCode: string;
	cmrTransSalePoints: string;
	cmrTransConfirmacion: string;
	cmrLimitAmount: string;
	cmrTransAnularSP: string;
	cmrOperatorReq: string;
	cmrTransCierre: string;
	nmrCuentaLocal: string;
	nmrCuentaExtranjera: string;
	cmrTransPoints: string;
	cmrTelephoneOperatorCode: string;
	cmrTransService: string;
	cmrDownloadProfile: string;
	cmrAdministratorKey: string;
	cmrSaldoAmountDollar: string;
	dmrContactName: string;
	cmrTransPagoService: string;
	cmrFlagBatchClose: string;

	cmrAcceptCompanyPayment:string;

	cmrCountryCode: string;
	
	departamento: string;
	provincia: string;
	distrito: string;
	cmrDownloadProfileName: string;

}
